### ISSUE TITLE
.html to .ejs file

### ISSUE THREAD

**Issue by Pharanyali** [Pharanyali/FinalProject#10]

**Comment by Pharanyali** [comment]
ea869465483c5cf8abccaa0efe5ca52e4d66bf2e change login.html to .ejs

**Comment by Pharanyali** [comment]
a2137d6e5e075463f558a4343e9b63060609fc44 change index.html to .ejs file

**Comment by JaruwithBub** [comment]
6b80156fdad62644ca4f076837225b8f3760b5ff login.html to ejs file
