### ISSUE TITLE
create order page

### ISSUE THREAD

**Issue by Pharanyali** [Pharanyali/FinalProject#3]

**Comment by JaruwithBub** [comment]
307bb41ffdda5ef2881e9ae5ba34f5a1be74c634 create order page

**Comment by JaruwithBub** [comment]
853e8b64b333745c0ce5cc77301ac6045e52804d user can add multiple order

**Comment by JaruwithBub** [comment]
83850061ff263689a3bc87fd0f8d012df4413dd8 add navbar for index.html
